language: csharp
script:
  - xbuild /p:Configuration=Debug OptField.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore OptField.sln
after_script:
  - nunit-console OptFieldsTests/bin/Debug/OptFieldsTests.dll